### ISSUE TITLE
error when not specifying validation sets?

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/NEAT#13]
When these two keys are missing in the yaml:

pos_validation
neg_validation

Then get the following error:

can't find key in YAML:  'pos_validation'
can't find key in YAML:  'neg_validation'
Traceback (most recent call last):
  File "/global/scratch/marcin/N2V/NEAT/venv/bin/neat", line 10, in <module>
    sys.exit(cli())
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/neat/cli.py", line 61, in run
    yhelp.edge_embedding_method())
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/neat/link_prediction/model.py", line 71, in make_link_prediction_data
    these_params.update(graph_args)
TypeError: 'NoneType' object is not iterable

**Comment by justaddcoffee** [comment]
It'd be helpful to have the YAML you are using

**Comment by justaddcoffee** [comment]
Also it'd be helpful to have the graphs if possible. 

These are likely just harmless warnings:
```
can't find key in YAML: 'pos_validation'
can't find key in YAML: 'neg_validation'
```

The error is here:
```
File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/neat/link_prediction/model.py", line 71, in make_link_prediction_data
these_params.update(graph_args)
TypeError: 'NoneType' object is not iterable
```

**Comment by realmarcin** [comment]
Here is another potentially related error:

can't find key in YAML:  'pos_validation'
can't find key in YAML:  'neg_validation'
Traceback (most recent call last):
  File "/global/scratch/marcin/N2V/NEAT/venv/bin/neat", line 10, in <module>
    sys.exit(cli())
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/neat/cli.py", line 61, in run
    yhelp.edge_embedding_method())
  File "/global/scratch/marcin/N2V/NEAT/venv/lib/python3.7/site-packages/neat/link_prediction/model.py", line 71, in make_link_prediction_data
    these_params.update(graph_args)
TypeError: 'NoneType' object is not iterable

**Comment by justaddcoffee** [comment]
I think I'd need the graph files (nodes and edges tsv) to figure out what the problem is here. Seems to be an issue parsing the callbacks for MLP [here](https://github.com/Knowledge-Graph-Hub/NEAT/blob/05c2e1801944e4ef865b34fbba95131ccff55a0d/yaml_ml_instructions/IMGVR_sample.yaml#L137).

It's nothing to do with these warning messages:
```
can't find key in YAML: 'pos_validation'
can't find key in YAML: 'neg_validation'
```
