### ISSUE TITLE
history.to_json() is None

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/NEAT#35]
Running ```neat run --config tests/resources/test.yaml```
has the following result:

```
  0% 0/4 [00:00<?, ?it/s]2021-11-18 18:47:17.046285: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
WARNING:root:Can't find key node_path in graph_data - skipping (possibly harmless)
WARNING:root:Can't find key node_path in graph_data - skipping (possibly harmless)
WARNING:root:Can't find key node_path in graph_data - skipping (possibly harmless)
tcmalloc: large alloc 1635311616 bytes == 0x5565d5aa6000 @  0x7f420b27c1e7 0x7f42055cd46e 0x7f420561dc7b 0x7f420561e35f 0x7f42056c0103 0x5565905a2544 0x5565905a2240 0x556590616627 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x556590610ced 0x5565905a3bda 0x556590611915 0x556590610ced 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x556590610ced 0x5565905a5cfe
tcmalloc: large alloc 1635311616 bytes == 0x556637234000 @  0x7f420b27c1e7 0x7f42055cd46e 0x7f420561dc7b 0x7f420561e35f 0x7f42056c0103 0x5565905a2544 0x5565905a2240 0x556590616627 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x556590610ced 0x5565905a3bda 0x556590611915 0x556590610ced 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x556590610ced 0x5565905a5cfe
tcmalloc: large alloc 1635311616 bytes == 0x556637234000 @  0x7f420b27c1e7 0x7f42055cd46e 0x7f420561dc7b 0x7f420561e35f 0x7f42056c0103 0x5565905a2544 0x5565905a2240 0x556590616627 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x556590610ced 0x5565905a3bda 0x556590611915 0x556590610ced 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x556590610ced 0x5565905a5cfe
tcmalloc: large alloc 1635311616 bytes == 0x5566989c2000 @  0x7f420b27c1e7 0x7f42055cd46e 0x7f420561dc7b 0x7f420561e35f 0x7f42056c0103 0x5565905a2544 0x5565905a2240 0x556590616627 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x556590610ced 0x5565905a3bda 0x556590611915 0x556590610ced 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565906109ee 0x5565905a3bda 0x556590612737 0x556590610ced 0x5565905a5cfe
tcmalloc: large alloc 3270615040 bytes == 0x5566fa978000 @  0x7f420b27c1e7 0x7f42055cd46e 0x7f420561dc7b 0x7f420561dd18 0x7f42056c5010 0x7f42056c573c 0x7f42056c585d 0x5565905a4749 0x7f420560aef7 0x5565905a2437 0x5565905a2240 0x556590615973 0x5565906109ee 0x5565905a3bda 0x556590615d00 0x5565904e2d14 0x7f420560aef7 0x5565905a2437 0x5565905a2240 0x556590615973 0x5565906109ee 0x5565905a3bda 0x556590615d00 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565905a3afa 0x556590615d00 0x5565906109ee 0x5565904e2e2b 0x556590612fe4
tcmalloc: large alloc 3270615040 bytes == 0x5567bd892000 @  0x7f420b27c1e7 0x7f42055cd46e 0x7f420561dc7b 0x7f420561dd18 0x7f42056b03a9 0x7f42056b2ab5 0x55659068a409 0x556590611e7a 0x5565906109ee 0x5565905a3bda 0x556590612737 0x5565905a3afa 0x556590615d00 0x5565906109ee 0x5565904e2e2b 0x556590612fe4 0x5565906109ee 0x5565905a448c 0x5565905a4698 0x556590612fe4 0x5565905a3afa 0x556590611c0d 0x556590610ced 0x5565905a3bda 0x556590611c0d 0x5565906109ee 0x5565905a4271 0x5565905a4698 0x556590612fe4 0x5565906109ee 0x5565905a4271
2021-11-18 18:48:08.252436: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 1635305056 exceeds 10% of free system memory.
14719/14719 [==============================] - 147s 10ms/step - loss: 0.2194 - auprc: 0.9560 - auroc: 0.9626 - Recall: 0.9859 - Precision: 0.8567 - accuracy: 0.9105 - val_loss: 0.2358 - val_auprc: 0.9588 - val_auroc: 0.9634 - val_Recall: 0.9745 - val_Precision: 0.8537 - val_accuracy: 0.9037
  0% 0/4 [03:21<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/neat", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/neat/cli.py", line 71, in run
    f.write(history.to_json())
AttributeError: 'NoneType' object has no attribute 'to_json'
```

**Comment by justaddcoffee** [comment]
closed by #34
