### ISSUE TITLE
Scheduled NEAT runs fail due to extra `graph_path` keyword

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/NEAT#73]
NEAT configs with the `graph_args` value lead to the following error when the scheduler attempts to run them:

```
15:37:00  Traceback (most recent call last):
15:37:00    File "/home/jenkinsuser/anaconda3/bin/neat", line 8, in <module>
15:37:00      sys.exit(cli())
15:37:00    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
15:37:00      return self.main(*args, **kwargs)
15:37:00    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
15:37:00      rv = self.invoke(ctx)
15:37:00    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
15:37:00      return _process_result(sub_ctx.command.invoke(sub_ctx))
15:37:00    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
15:37:00      return ctx.invoke(self.callback, **ctx.params)
15:37:00    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
15:37:00      return callback(*args, **kwargs)
15:37:00    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/neat/cli.py", line 55, in run
15:37:00      make_node_embeddings(**node_embedding_args)
15:37:00    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/neat/graph_embedding/graph_embedding.py", line 47, in make_node_embeddings
15:37:00      graph: Graph = Graph.from_csv(**main_graph_args)
15:37:00  TypeError: Graph.from_csv() got an unexpected keyword argument: graph_path
```

This makes sense - the `ensmallen` ` Graph.from_csv()` doesn't know what to do with this keyword, as it's specific to NEAT.
It should be removed before passing kwargs to `from_csv()`.

**Comment by caufieldjh** [comment]
Reopening as this appears to still be happening:
```
12:10:53  Traceback (most recent call last):
12:10:53    File "/home/jenkinsuser/anaconda3/bin/neat", line 8, in <module>
12:10:53      sys.exit(cli())
12:10:53    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
12:10:53      return self.main(*args, **kwargs)
12:10:53    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
12:10:53      rv = self.invoke(ctx)
12:10:53    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
12:10:53      return _process_result(sub_ctx.command.invoke(sub_ctx))
12:10:53    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
12:10:53      return ctx.invoke(self.callback, **ctx.params)
12:10:53    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
12:10:53      return callback(*args, **kwargs)
12:10:53    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/neat/cli.py", line 91, in run
12:10:53      edge_method=yhelp.get_edge_embedding_method(classifier),
12:10:53    File "/home/jenkinsuser/anaconda3/lib/python3.7/site-packages/neat/link_prediction/model.py", line 73, in make_train_valid_data
12:10:53      graphs = {"pos_training": Graph.from_csv(**training_graph_args)}
12:10:53  TypeError: Graph.from_csv() got an unexpected keyword argument: graph_path
```

This time, the `link_prediction` module is throwing it rather than `graph_embedding`.
